//! E2E tests for the onboarding flow.

use super::harness::SimseTestHarness;
use simse_tui::app::{AppMessage, Screen};
use simse_tui::onboarding::OnboardingState;

#[test]
fn fresh_app_needs_setup() {
	let h = SimseTestHarness::new();
	assert!(h.app.onboarding.needs_setup);
	assert!(!h.app.onboarding.welcome_shown);
}

#[test]
fn welcome_message_mentions_setup() {
	// The welcome message (generated by onboarding::welcome_message())
	// should contain key setup instructions
	let lines = simse_tui::onboarding::welcome_message();
	let text: String = lines
		.iter()
		.flat_map(|line| line.spans.iter().map(|s| s.content.to_string()))
		.collect::<Vec<_>>()
		.join(" ");
	assert!(text.contains("Welcome"));
	assert!(text.contains("ACP"));
	assert!(text.contains("/help"));
}

#[test]
fn setup_command_opens_wizard() {
	let mut h = SimseTestHarness::new();
	h.submit("/setup");
	assert!(matches!(
		h.current_screen(),
		Screen::Setup { preset: None }
	));
}

#[test]
fn setup_preset_opens_wizard_with_preset() {
	let mut h = SimseTestHarness::new();
	h.submit("/setup ollama");
	assert!(matches!(
		h.current_screen(),
		Screen::Setup {
			preset: Some(p)
		} if p == "ollama"
	));
}

#[test]
fn factory_reset_triggers_onboarding_restart() {
	let mut h = SimseTestHarness::new();
	// Start with onboarding satisfied
	h.app.onboarding = OnboardingState {
		needs_setup: false,
		welcome_shown: true,
	};
	h.app.server_name = Some("test-server".into());

	// Submit factory-reset -> shows confirm dialog
	h.submit("/factory-reset");
	assert!(matches!(h.current_screen(), Screen::Confirm { .. }));

	// Confirm it
	h.press_enter();
	assert!(h.app.pending_bridge_action.is_some());

	// Simulate bridge result
	h.send(AppMessage::BridgeResult {
		action: "factory-reset".into(),
		text: "Factory reset complete.".into(),
		is_error: false,
	});

	// Onboarding should be restarted
	assert!(h.app.onboarding.needs_setup);
	assert!(!h.app.onboarding.welcome_shown);
	assert!(h.app.server_name.is_none());
}

#[test]
fn factory_reset_project_does_not_trigger_onboarding() {
	let mut h = SimseTestHarness::new();
	h.app.onboarding = OnboardingState {
		needs_setup: false,
		welcome_shown: true,
	};
	h.app.server_name = Some("test-server".into());

	// Submit factory-reset-project -> shows confirm dialog
	h.submit("/factory-reset-project");
	assert!(matches!(h.current_screen(), Screen::Confirm { .. }));

	// Confirm it
	h.press_enter();

	// Simulate bridge result
	h.send(AppMessage::BridgeResult {
		action: "factory-reset-project".into(),
		text: "Project config reset.".into(),
		is_error: false,
	});

	// Onboarding should NOT be restarted (project reset != global reset)
	assert!(!h.app.onboarding.needs_setup);
	assert!(h.app.server_name.is_some());
}
