name = "simse-cloud"
compatibility_date = "2025-04-01"
pages_build_output_dir = "./build/client"

[vars]
APP_URL = "https://app.simse.dev"

routes = [{ pattern = "app.simse.dev", custom_domain = true }]

[durable_objects]
bindings = [{ name = "TUNNEL_SESSION", class_name = "TunnelSession" }]

[[migrations]]
tag = "v1"
new_classes = ["TunnelSession"]

[[queues.producers]]
queue = "simse-cloud-analytics"
binding = "ANALYTICS_QUEUE"

# --- Environments ---

[env.staging]
name = "simse-cloud-staging"

[env.staging.vars]
APP_URL = "https://simse-cloud-staging.pages.dev"

[[env.staging.queues.producers]]
queue = "simse-cloud-analytics-staging"
binding = "ANALYTICS_QUEUE"

[env.production]
name = "simse-cloud"
routes = [{ pattern = "app.simse.dev", custom_domain = true }]

[[env.production.queues.producers]]
queue = "simse-cloud-analytics"
binding = "ANALYTICS_QUEUE"

[env.production.vars]
APP_URL = "https://app.simse.dev"
