name = "simse-cloud"
compatibility_date = "2025-04-01"
pages_build_output_dir = "./build/client"

[vars]
APP_URL = "https://app.simse.dev"
AUTH_API_URL = "https://auth.test.internal"

routes = [{ pattern = "app.simse.dev", custom_domain = true }]

[durable_objects]
bindings = [{ name = "TUNNEL_SESSION", class_name = "TunnelSession" }]

[[migrations]]
tag = "v1"
new_classes = ["TunnelSession"]

[analytics_engine]
dataset = "simse-analytics"
binding = "ANALYTICS"

# --- Environments ---

[env.staging]
name = "simse-cloud-staging"

[env.staging.vars]
APP_URL = "https://simse-cloud-staging.pages.dev"
AUTH_API_URL = "https://auth.test.internal"

[env.production]
name = "simse-cloud"
routes = [{ pattern = "app.simse.dev", custom_domain = true }]

[env.production.vars]
APP_URL = "https://app.simse.dev"
AUTH_API_URL = "https://auth.simse.dev"
