name = "simse-mailer"
compatibility_date = "2025-04-01"
main = "src/index.ts"

[[d1_databases]]
binding = "DB"
database_name = "simse-mailer-db"
database_id = "PLACEHOLDER_FILL_AFTER_CREATION"

[[secrets_store.bindings]]
binding = "SECRETS"
store_id = "PLACEHOLDER_REPLACE_WITH_STORE_ID"

[[queues.consumers]]
queue = "simse-auth-comms"

[[queues.consumers]]
queue = "simse-api-comms"

[[queues.consumers]]
queue = "simse-landing-comms"
