name = "simse-landing"
compatibility_date = "2026-02-28"
pages_build_output_dir = "./build/client"

[[d1_databases]]
binding = "DB"
database_name = "simse_waitlist"
database_id = "e5659e77-878c-440c-bbf6-dd74a324938b"

[[queues.producers]]
queue = "simse-landing-comms"
binding = "COMMS_QUEUE"

[[queues.producers]]
queue = "simse-landing-analytics"
binding = "ANALYTICS_QUEUE"

[env.preview]
name = "simse-landing-preview"

[[env.preview.d1_databases]]
binding = "DB"
database_name = "simse-waitlist-staging"
database_id = "PLACEHOLDER_STAGING_WAITLIST_DB_ID"

[[env.preview.queues.producers]]
queue = "simse-landing-comms-staging"
binding = "COMMS_QUEUE"

[[env.preview.queues.producers]]
queue = "simse-landing-analytics-staging"
binding = "ANALYTICS_QUEUE"

[env.production]
name = "simse-landing"

[[env.production.d1_databases]]
binding = "DB"
database_name = "simse_waitlist"
database_id = "e5659e77-878c-440c-bbf6-dd74a324938b"

[[env.production.queues.producers]]
queue = "simse-landing-comms"
binding = "COMMS_QUEUE"

[[env.production.queues.producers]]
queue = "simse-landing-analytics"
binding = "ANALYTICS_QUEUE"
