inheritedBy:
  toolchains: ['bun', 'javascript', 'typescript']

tasks:
  lint:
    command: 'bunx biome check .'
  setup:
    command: 'bun install'
  build:
    command: 'bun run build'
  dev:
    command: 'bun run dev'
    options:
      persistent: true
      runInCI: false
  test:
    command: 'bun run typecheck'
  start:
    command: 'bun run start'
    options:
      persistent: true
