name = "simse-api"
compatibility_date = "2025-04-01"
main = "src/index.ts"

[[d1_databases]]
binding = "DB"
database_name = "simse-api-db"
database_id = "a2a07725-b216-4ab0-bb60-6fd83db97e3d"

# Secrets (set via `wrangler secret put`):
# PAYMENTS_API_URL
# PAYMENTS_API_SECRET
# MAILER_API_URL
# MAILER_API_SECRET
